global using System.Diagnostics;
global using CineVault.API.Controllers.Requests;
global using CineVault.API.Controllers.Responses;
global using CineVault.API.Entities;
global using CineVault.API.Extensions;
global using CineVault.API.Middleware;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Serilog;
global using Serilog.Events;
global using ILogger = Serilog.ILogger;